name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
#   build-windows:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Install ROS
#         uses: ros-tooling/setup-ros@v0.7
#         with:
#           required-ros-distributions: jazzy

#       - name: Setup Rust cache
#         uses: actions/cache@v4
#         with:
#           path: |
#               ~/.cargo/bin/
#               ~/.cargo/registry/index/
#               ~/.cargo/registry/cache/
#               ~/.cargo/git/db/
#               target/
#           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

#       - name: Compile binary
#         run: C:\dev\jazzy\ros2-windows\local_setup.ps1 ; cargo build --release

#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: ${{ runner.os }}
#           path: target/release/intrepid-ros-monitor.exe
#           retention-days: 1

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ROS
        run: |
            sudo apt install software-properties-common
            sudo add-apt-repository universe
            sudo apt update && sudo apt install curl -y
            sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
            cat /etc/apt/sources.list.d/ros2.list
            sudo apt update
            sudo apt-get install ros-humble-ros-base

      - name: Setup Rust cache
        uses: actions/cache@v4
        with:
          path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Compile binary
        run: source /opt/ros/humble/local_setup.bash ; cargo build --release ; strip target/release/intrepid-ros-monitor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: target/release/intrepid-ros-monitor
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - name: Create test file
        run: shasum Linux/* > body.md
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          #allowUpdates: true
          artifacts: "Linux/*"
          artifactErrorsFailBuild: true
          bodyFile: "body.md"
          #draft: true
